/*
###############################################################
#  Generated by:      Cadence Innovus 19.18-s072_1
#  OS:                Linux x86_64(Host ID rivendell.ecen.okstate.edu)
#  Generated on:      Tue Aug  2 14:53:58 2022
#  Design:            mult_seq
#  Command:           saveNetlist -excludeLeafCell final.v
###############################################################
*/
module flopenr_WIDTH8 (
	clk, 
	reset, 
	en, 
	d, 
	q, 
	p1, 
	p2, 
	p3, 
	p4, 
	p5);
   input clk;
   input reset;
   input en;
   input [7:0] d;
   output [7:0] q;
   output p1;
   output p2;
   output p3;
   output p4;
   output p5;

   // Internal wires
   wire FE_PHN39_sum_q_7;
   wire FE_PHN38_sum_q_1;
   wire FE_PHN37_n_4;
   wire FE_PHN36_q_0_58;
   wire FE_PHN35_sum_q_1;
   wire FE_PHN34_sum_q_6;
   wire FE_PHN33_sum_q_5;
   wire FE_PHN32_q_4_62;
   wire FE_PHN31_n_7;
   wire FE_PHN30_sum_q_6;
   wire FE_PHN29_n_9;
   wire FE_PHN28_sum_q_7;
   wire FE_PHN27_sum_q_5;
   wire FE_PHN26_n_10;
   wire FE_PHN25_sum_q_3;
   wire FE_PHN24_n_9;
   wire FE_PHN23_n_7;
   wire FE_PHN20_sum_q_6;
   wire FE_PHN19_n_10;
   wire FE_PHN18_sum_q_5;
   wire FE_PHN17_sum_q_4;
   wire FE_PHN16_sum_q_3;
   wire FE_PHN15_n_18;
   wire FE_PHN14_n_11;
   wire FE_PHN13_n_9;
   wire FE_PHN12_n_4;
   wire FE_PHN11_n_7;
   wire FE_PHN8_q_0_58;
   wire FE_PHN7_n_18;
   wire FE_PHN6_n_4;
   wire FE_PHN5_n_5;
   wire FE_PHN4_n_6;
   wire FE_PHN3_n_9;
   wire FE_PHN2_n_11;
   wire FE_PHN0_q_0_58;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire n_0;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire \q[0]_58 ;
   wire \q[3]_61 ;
   wire \q[4]_62 ;

   sky130_osu_sc_18T_ms__buf_l FE_PHC39_sum_q_7 (.Y(FE_PHN39_sum_q_7),
	.A(p5));
   sky130_osu_sc_18T_ms__buf_l FE_PHC38_sum_q_1 (.Y(FE_PHN38_sum_q_1),
	.A(FE_PHN35_sum_q_1));
   sky130_osu_sc_18T_ms__buf_l FE_PHC37_n_4 (.Y(FE_PHN37_n_4),
	.A(FE_PHN12_n_4));
   sky130_osu_sc_18T_ms__buf_l FE_PHC36_q_0_58 (.Y(FE_PHN36_q_0_58),
	.A(FE_PHN8_q_0_58));
   sky130_osu_sc_18T_ms__buf_l FE_PHC35_sum_q_1 (.Y(FE_PHN35_sum_q_1),
	.A(p1));
   sky130_osu_sc_18T_ms__buf_4 FE_PHC34_sum_q_6 (.Y(FE_PHN34_sum_q_6),
	.A(FE_PHN20_sum_q_6));
   sky130_osu_sc_18T_ms__buf_l FE_PHC33_sum_q_5 (.Y(FE_PHN33_sum_q_5),
	.A(p3));
   sky130_osu_sc_18T_ms__buf_4 FE_PHC32_q_4_62 (.Y(\q[4]_62 ),
	.A(FE_PHN32_q_4_62));
   sky130_osu_sc_18T_ms__buf_l FE_PHC31_n_7 (.Y(FE_PHN31_n_7),
	.A(FE_PHN23_n_7));
   sky130_osu_sc_18T_ms__buf_4 FE_PHC30_sum_q_6 (.Y(FE_PHN30_sum_q_6),
	.A(FE_PHN34_sum_q_6));
   sky130_osu_sc_18T_ms__buf_l FE_PHC29_n_9 (.Y(FE_PHN29_n_9),
	.A(FE_PHN24_n_9));
   sky130_osu_sc_18T_ms__buf_l FE_PHC28_sum_q_7 (.Y(FE_PHN28_sum_q_7),
	.A(q[7]));
   sky130_osu_sc_18T_ms__buf_l FE_PHC27_sum_q_5 (.Y(FE_PHN27_sum_q_5),
	.A(FE_PHN18_sum_q_5));
   sky130_osu_sc_18T_ms__buf_l FE_PHC26_n_10 (.Y(FE_PHN26_n_10),
	.A(FE_PHN19_n_10));
   sky130_osu_sc_18T_ms__buf_l FE_PHC25_sum_q_3 (.Y(FE_PHN25_sum_q_3),
	.A(FE_PHN16_sum_q_3));
   sky130_osu_sc_18T_ms__buf_4 FE_PHC24_n_9 (.Y(FE_PHN24_n_9),
	.A(FE_PHN3_n_9));
   sky130_osu_sc_18T_ms__buf_l FE_PHC23_n_7 (.Y(FE_PHN23_n_7),
	.A(FE_PHN11_n_7));
   sky130_osu_sc_18T_ms__buf_l FE_PHC22_sum_q_7 (.Y(p5),
	.A(FE_PHN28_sum_q_7));
   sky130_osu_sc_18T_ms__buf_l FE_PHC21_sum_q_2 (.Y(p4),
	.A(q[2]));
   sky130_osu_sc_18T_ms__buf_4 FE_PHC20_sum_q_6 (.Y(FE_PHN20_sum_q_6),
	.A(p2));
   sky130_osu_sc_18T_ms__buf_4 FE_PHC19_n_10 (.Y(FE_PHN19_n_10),
	.A(n_10));
   sky130_osu_sc_18T_ms__buf_l FE_PHC18_sum_q_5 (.Y(FE_PHN18_sum_q_5),
	.A(FE_PHN33_sum_q_5));
   sky130_osu_sc_18T_ms__buf_4 FE_PHC17_sum_q_4 (.Y(FE_PHN17_sum_q_4),
	.A(q[4]));
   sky130_osu_sc_18T_ms__buf_4 FE_PHC16_sum_q_3 (.Y(FE_PHN16_sum_q_3),
	.A(q[3]));
   sky130_osu_sc_18T_ms__buf_8 FE_PHC15_n_18 (.Y(FE_PHN15_n_18),
	.A(n_18));
   sky130_osu_sc_18T_ms__buf_8 FE_PHC14_n_11 (.Y(n_11),
	.A(FE_PHN14_n_11));
   sky130_osu_sc_18T_ms__buf_8 FE_PHC13_n_9 (.Y(FE_PHN13_n_9),
	.A(FE_PHN29_n_9));
   sky130_osu_sc_18T_ms__buf_8 FE_PHC12_n_4 (.Y(FE_PHN12_n_4),
	.A(FE_PHN6_n_4));
   sky130_osu_sc_18T_ms__buf_8 FE_PHC11_n_7 (.Y(FE_PHN11_n_7),
	.A(n_7));
   sky130_osu_sc_18T_ms__buf_8 FE_PHC10_sum_q_5 (.Y(p3),
	.A(q[5]));
   sky130_osu_sc_18T_ms__buf_l FE_PHC9_sum_q_6 (.Y(p2),
	.A(q[6]));
   sky130_osu_sc_18T_ms__buf_8 FE_PHC8_q_0_58 (.Y(FE_PHN8_q_0_58),
	.A(FE_PHN0_q_0_58));
   sky130_osu_sc_18T_ms__buf_8 FE_PHC7_n_18 (.Y(FE_PHN7_n_18),
	.A(FE_PHN15_n_18));
   sky130_osu_sc_18T_ms__buf_8 FE_PHC6_n_4 (.Y(FE_PHN6_n_4),
	.A(n_4));
   sky130_osu_sc_18T_ms__buf_8 FE_PHC5_n_5 (.Y(FE_PHN5_n_5),
	.A(n_5));
   sky130_osu_sc_18T_ms__buf_8 FE_PHC4_n_6 (.Y(FE_PHN4_n_6),
	.A(n_6));
   sky130_osu_sc_18T_ms__buf_8 FE_PHC3_n_9 (.Y(FE_PHN3_n_9),
	.A(n_9));
   sky130_osu_sc_18T_ms__buf_8 FE_PHC2_n_11 (.Y(FE_PHN2_n_11),
	.A(n_11));
   sky130_osu_sc_18T_ms__buf_l FE_PHC1_sum_q_1 (.Y(p1),
	.A(q[1]));
   sky130_osu_sc_18T_ms__buf_8 FE_PHC0_q_0_58 (.Y(FE_PHN0_q_0_58),
	.A(\q[0]_58 ));
   sky130_osu_sc_18T_ms__dff_1 \q_reg[3]  (.Q(UNCONNECTED),
	.QN(\q[3]_61 ),
	.CK(clk),
	.D(n_17));
   sky130_osu_sc_18T_ms__dff_1 \q_reg[2]  (.Q(q[2]),
	.QN(UNCONNECTED0),
	.CK(clk),
	.D(n_12));
   sky130_osu_sc_18T_ms__dff_1 \q_reg[0]  (.Q(UNCONNECTED1),
	.QN(\q[0]_58 ),
	.CK(clk),
	.D(n_15));
   sky130_osu_sc_18T_ms__dff_1 \q_reg[4]  (.Q(UNCONNECTED2),
	.QN(FE_PHN32_q_4_62),
	.CK(clk),
	.D(FE_PHN7_n_18));
   sky130_osu_sc_18T_ms__dff_1 \q_reg[6]  (.Q(q[6]),
	.QN(UNCONNECTED3),
	.CK(clk),
	.D(n_13));
   sky130_osu_sc_18T_ms__dff_1 \q_reg[5]  (.Q(q[5]),
	.QN(UNCONNECTED4),
	.CK(clk),
	.D(n_19));
   sky130_osu_sc_18T_ms__dff_1 \q_reg[1]  (.Q(q[1]),
	.QN(UNCONNECTED5),
	.CK(clk),
	.D(n_16));
   sky130_osu_sc_18T_ms__dff_1 \q_reg[7]  (.Q(q[7]),
	.QN(UNCONNECTED6),
	.CK(clk),
	.D(n_14));
   sky130_osu_sc_18T_ms__nor2_1 g27__2398 (.Y(n_19),
	.A(reset),
	.B(FE_PHN5_n_5));
   sky130_osu_sc_18T_ms__nor2_1 g28__5107 (.Y(n_18),
	.A(reset),
	.B(n_8));
   sky130_osu_sc_18T_ms__nor2_1 g29__6260 (.Y(n_17),
	.A(reset),
	.B(FE_PHN2_n_11));
   sky130_osu_sc_18T_ms__nor2_1 g30__4319 (.Y(n_16),
	.A(reset),
	.B(FE_PHN31_n_7));
   sky130_osu_sc_18T_ms__nor2_1 g31__8428 (.Y(n_15),
	.A(reset),
	.B(FE_PHN26_n_10));
   sky130_osu_sc_18T_ms__nor2_1 g32__5526 (.Y(n_14),
	.A(reset),
	.B(FE_PHN37_n_4));
   sky130_osu_sc_18T_ms__nor2_1 g33__6783 (.Y(n_13),
	.A(reset),
	.B(FE_PHN4_n_6));
   sky130_osu_sc_18T_ms__nor2_1 g34__3680 (.Y(n_12),
	.A(reset),
	.B(FE_PHN13_n_9));
   sky130_osu_sc_18T_ms__aoi22_l g35__1617 (.Y(FE_PHN14_n_11),
	.A0(n_0),
	.A1(FE_PHN25_sum_q_3),
	.B0(d[3]),
	.B1(en));
   sky130_osu_sc_18T_ms__aoi22_l g36__2802 (.Y(n_10),
	.A0(n_0),
	.A1(q[0]),
	.B0(d[0]),
	.B1(en));
   sky130_osu_sc_18T_ms__aoi22_l g37__1705 (.Y(n_9),
	.A0(n_0),
	.A1(p4),
	.B0(d[2]),
	.B1(en));
   sky130_osu_sc_18T_ms__aoi22_l g38__5122 (.Y(n_8),
	.A0(n_0),
	.A1(FE_PHN17_sum_q_4),
	.B0(d[4]),
	.B1(en));
   sky130_osu_sc_18T_ms__aoi22_l g39__8246 (.Y(n_7),
	.A0(n_0),
	.A1(FE_PHN38_sum_q_1),
	.B0(d[1]),
	.B1(en));
   sky130_osu_sc_18T_ms__aoi22_l g40__7098 (.Y(n_6),
	.A0(n_0),
	.A1(FE_PHN30_sum_q_6),
	.B0(d[6]),
	.B1(en));
   sky130_osu_sc_18T_ms__aoi22_l g41__6131 (.Y(n_5),
	.A0(n_0),
	.A1(FE_PHN27_sum_q_5),
	.B0(d[5]),
	.B1(en));
   sky130_osu_sc_18T_ms__aoi22_l g42__1881 (.Y(n_4),
	.A0(n_0),
	.A1(FE_PHN39_sum_q_7),
	.B0(d[7]),
	.B1(en));
   sky130_osu_sc_18T_ms__inv_1 g43 (.Y(q[3]),
	.A(\q[3]_61 ));
   sky130_osu_sc_18T_ms__inv_1 g44 (.Y(q[4]),
	.A(\q[4]_62 ));
   sky130_osu_sc_18T_ms__inv_1 g45 (.Y(q[0]),
	.A(FE_PHN36_q_0_58));
   sky130_osu_sc_18T_ms__inv_1 g46 (.Y(n_0),
	.A(en));
endmodule

module mult_seq (
	a, 
	b, 
	clk, 
	reset, 
	en, 
	sum_q);
   input [3:0] a;
   input [3:0] b;
   input clk;
   input reset;
   input en;
   output [7:0] sum_q;

   // Internal wires
   wire FE_PHN22_sum_q_7;
   wire FE_PHN21_sum_q_2;
   wire FE_PHN10_sum_q_5;
   wire FE_PHN9_sum_q_6;
   wire FE_PHN1_sum_q_1;
   wire [7:0] sum;
   wire csa_tree_add1_add_30_16_groupi_n_0;
   wire csa_tree_add1_add_30_16_groupi_n_1;
   wire csa_tree_add1_add_30_16_groupi_n_4;
   wire csa_tree_add1_add_30_16_groupi_n_5;
   wire csa_tree_add1_add_30_16_groupi_n_6;
   wire csa_tree_add1_add_30_16_groupi_n_7;
   wire csa_tree_add1_add_30_16_groupi_n_8;
   wire csa_tree_add1_add_30_16_groupi_n_9;
   wire csa_tree_add1_add_30_16_groupi_n_10;
   wire csa_tree_add1_add_30_16_groupi_n_11;
   wire csa_tree_add1_add_30_16_groupi_n_12;
   wire csa_tree_add1_add_30_16_groupi_n_13;
   wire csa_tree_add1_add_30_16_groupi_n_14;
   wire csa_tree_add1_add_30_16_groupi_n_15;
   wire csa_tree_add1_add_30_16_groupi_n_16;
   wire csa_tree_add1_add_30_16_groupi_n_17;
   wire csa_tree_add1_add_30_16_groupi_n_18;
   wire csa_tree_add1_add_30_16_groupi_n_19;
   wire csa_tree_add1_add_30_16_groupi_n_20;
   wire csa_tree_add1_add_30_16_groupi_n_21;
   wire csa_tree_add1_add_30_16_groupi_n_23;
   wire csa_tree_add1_add_30_16_groupi_n_24;
   wire csa_tree_add1_add_30_16_groupi_n_25;
   wire csa_tree_add1_add_30_16_groupi_n_26;
   wire csa_tree_add1_add_30_16_groupi_n_27;
   wire csa_tree_add1_add_30_16_groupi_n_28;
   wire csa_tree_add1_add_30_16_groupi_n_30;
   wire csa_tree_add1_add_30_16_groupi_n_31;
   wire csa_tree_add1_add_30_16_groupi_n_32;
   wire csa_tree_add1_add_30_16_groupi_n_33;
   wire csa_tree_add1_add_30_16_groupi_n_34;
   wire csa_tree_add1_add_30_16_groupi_n_35;
   wire csa_tree_add1_add_30_16_groupi_n_36;
   wire csa_tree_add1_add_30_16_groupi_n_39;
   wire csa_tree_add1_add_30_16_groupi_n_40;
   wire csa_tree_add1_add_30_16_groupi_n_41;
   wire csa_tree_add1_add_30_16_groupi_n_42;
   wire csa_tree_add1_add_30_16_groupi_n_43;
   wire csa_tree_add1_add_30_16_groupi_n_44;
   wire csa_tree_add1_add_30_16_groupi_n_45;
   wire csa_tree_add1_add_30_16_groupi_n_46;
   wire csa_tree_add1_add_30_16_groupi_n_47;
   wire csa_tree_add1_add_30_16_groupi_n_48;
   wire csa_tree_add1_add_30_16_groupi_n_49;
   wire csa_tree_add1_add_30_16_groupi_n_50;
   wire csa_tree_add1_add_30_16_groupi_n_52;
   wire csa_tree_add1_add_30_16_groupi_n_53;
   wire csa_tree_add1_add_30_16_groupi_n_54;
   wire csa_tree_add1_add_30_16_groupi_n_55;
   wire csa_tree_add1_add_30_16_groupi_n_56;
   wire csa_tree_add1_add_30_16_groupi_n_57;
   wire csa_tree_add1_add_30_16_groupi_n_59;
   wire csa_tree_add1_add_30_16_groupi_n_60;
   wire csa_tree_add1_add_30_16_groupi_n_62;
   wire csa_tree_add1_add_30_16_groupi_n_63;
   wire csa_tree_add1_add_30_16_groupi_n_64;
   wire csa_tree_add1_add_30_16_groupi_n_65;
   wire csa_tree_add1_add_30_16_groupi_n_66;
   wire csa_tree_add1_add_30_16_groupi_n_68;
   wire csa_tree_add1_add_30_16_groupi_n_69;
   wire csa_tree_add1_add_30_16_groupi_n_70;
   wire csa_tree_add1_add_30_16_groupi_n_71;
   wire csa_tree_add1_add_30_16_groupi_n_72;
   wire csa_tree_add1_add_30_16_groupi_n_73;
   wire csa_tree_add1_add_30_16_groupi_n_74;
   wire csa_tree_add1_add_30_16_groupi_n_75;
   wire csa_tree_add1_add_30_16_groupi_n_76;
   wire csa_tree_add1_add_30_16_groupi_n_77;
   wire csa_tree_add1_add_30_16_groupi_n_78;
   wire csa_tree_add1_add_30_16_groupi_n_79;
   wire csa_tree_add1_add_30_16_groupi_n_80;
   wire csa_tree_add1_add_30_16_groupi_n_81;
   wire csa_tree_add1_add_30_16_groupi_n_82;
   wire csa_tree_add1_add_30_16_groupi_n_84;
   wire csa_tree_add1_add_30_16_groupi_n_85;
   wire csa_tree_add1_add_30_16_groupi_n_87;
   wire csa_tree_add1_add_30_16_groupi_n_89;
   wire csa_tree_add1_add_30_16_groupi_n_91;
   wire csa_tree_add1_add_30_16_groupi_n_93;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;

   flopenr_WIDTH8 reg1 (.clk(clk),
	.reset(reset),
	.en(en),
	.d(sum),
	.q(sum_q),
	.p1(FE_PHN1_sum_q_1),
	.p2(FE_PHN9_sum_q_6),
	.p3(FE_PHN10_sum_q_5),
	.p4(FE_PHN21_sum_q_2),
	.p5(FE_PHN22_sum_q_7));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g417__5115 (.Y(sum[7]),
	.A(csa_tree_add1_add_30_16_groupi_n_93),
	.B(n_112));
   sky130_osu_sc_18T_ms__oai22_l csa_tree_add1_add_30_16_groupi_g418__7482 (.Y(csa_tree_add1_add_30_16_groupi_n_93),
	.A0(csa_tree_add1_add_30_16_groupi_n_78),
	.A1(csa_tree_add1_add_30_16_groupi_n_91),
	.B0(csa_tree_add1_add_30_16_groupi_n_55),
	.B1(csa_tree_add1_add_30_16_groupi_n_69));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g419__4733 (.Y(sum[6]),
	.A(csa_tree_add1_add_30_16_groupi_n_91),
	.B(csa_tree_add1_add_30_16_groupi_n_80));
   sky130_osu_sc_18T_ms__aoi22_l csa_tree_add1_add_30_16_groupi_g420__6161 (.Y(csa_tree_add1_add_30_16_groupi_n_91),
	.A0(csa_tree_add1_add_30_16_groupi_n_82),
	.A1(csa_tree_add1_add_30_16_groupi_n_89),
	.B0(csa_tree_add1_add_30_16_groupi_n_75),
	.B1(csa_tree_add1_add_30_16_groupi_n_70));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g421__9315 (.Y(sum[5]),
	.A(csa_tree_add1_add_30_16_groupi_n_89),
	.B(csa_tree_add1_add_30_16_groupi_n_84));
   sky130_osu_sc_18T_ms__oai22_l csa_tree_add1_add_30_16_groupi_g422__9945 (.Y(csa_tree_add1_add_30_16_groupi_n_89),
	.A0(csa_tree_add1_add_30_16_groupi_n_77),
	.A1(csa_tree_add1_add_30_16_groupi_n_87),
	.B0(csa_tree_add1_add_30_16_groupi_n_68),
	.B1(csa_tree_add1_add_30_16_groupi_n_65));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g423__2883 (.Y(sum[4]),
	.A(csa_tree_add1_add_30_16_groupi_n_87),
	.B(csa_tree_add1_add_30_16_groupi_n_79));
   sky130_osu_sc_18T_ms__aoi21_l csa_tree_add1_add_30_16_groupi_g424__2346 (.Y(csa_tree_add1_add_30_16_groupi_n_87),
	.A0(csa_tree_add1_add_30_16_groupi_n_46),
	.A1(csa_tree_add1_add_30_16_groupi_n_64),
	.B0(csa_tree_add1_add_30_16_groupi_n_85));
   sky130_osu_sc_18T_ms__xnor2_l csa_tree_add1_add_30_16_groupi_g425__1666 (.Y(sum[3]),
	.A(csa_tree_add1_add_30_16_groupi_n_74),
	.B(csa_tree_add1_add_30_16_groupi_n_81));
   sky130_osu_sc_18T_ms__nor2_1 csa_tree_add1_add_30_16_groupi_g426__7410 (.Y(csa_tree_add1_add_30_16_groupi_n_85),
	.A(csa_tree_add1_add_30_16_groupi_n_81),
	.B(csa_tree_add1_add_30_16_groupi_n_71));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g427__6417 (.Y(csa_tree_add1_add_30_16_groupi_n_84),
	.A(csa_tree_add1_add_30_16_groupi_n_75),
	.B(csa_tree_add1_add_30_16_groupi_n_70));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g428__5477 (.Y(sum[2]),
	.A(csa_tree_add1_add_30_16_groupi_n_59),
	.B(csa_tree_add1_add_30_16_groupi_n_73));
   sky130_osu_sc_18T_ms__or2_1 csa_tree_add1_add_30_16_groupi_g429__2398 (.Y(csa_tree_add1_add_30_16_groupi_n_82),
	.A(csa_tree_add1_add_30_16_groupi_n_70),
	.B(csa_tree_add1_add_30_16_groupi_n_75));
   sky130_osu_sc_18T_ms__aoi21_l csa_tree_add1_add_30_16_groupi_g430__5107 (.Y(csa_tree_add1_add_30_16_groupi_n_81),
	.A0(csa_tree_add1_add_30_16_groupi_n_63),
	.A1(FE_PHN21_sum_q_2),
	.B0(csa_tree_add1_add_30_16_groupi_n_76));
   sky130_osu_sc_18T_ms__xnor2_l csa_tree_add1_add_30_16_groupi_g431__6260 (.Y(csa_tree_add1_add_30_16_groupi_n_80),
	.A(csa_tree_add1_add_30_16_groupi_n_55),
	.B(csa_tree_add1_add_30_16_groupi_n_69));
   sky130_osu_sc_18T_ms__xnor2_l csa_tree_add1_add_30_16_groupi_g432__4319 (.Y(csa_tree_add1_add_30_16_groupi_n_79),
	.A(csa_tree_add1_add_30_16_groupi_n_68),
	.B(csa_tree_add1_add_30_16_groupi_n_65));
   sky130_osu_sc_18T_ms__and2_l csa_tree_add1_add_30_16_groupi_g433__8428 (.Y(csa_tree_add1_add_30_16_groupi_n_78),
	.A(csa_tree_add1_add_30_16_groupi_n_55),
	.B(csa_tree_add1_add_30_16_groupi_n_69));
   sky130_osu_sc_18T_ms__and2_1 csa_tree_add1_add_30_16_groupi_g434__5526 (.Y(csa_tree_add1_add_30_16_groupi_n_77),
	.A(csa_tree_add1_add_30_16_groupi_n_68),
	.B(csa_tree_add1_add_30_16_groupi_n_65));
   sky130_osu_sc_18T_ms__nor2_l csa_tree_add1_add_30_16_groupi_g435__6783 (.Y(csa_tree_add1_add_30_16_groupi_n_76),
	.A(csa_tree_add1_add_30_16_groupi_n_72),
	.B(csa_tree_add1_add_30_16_groupi_n_59));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g436__3680 (.Y(csa_tree_add1_add_30_16_groupi_n_75),
	.A(csa_tree_add1_add_30_16_groupi_n_62),
	.B(csa_tree_add1_add_30_16_groupi_n_52));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g437__1617 (.Y(csa_tree_add1_add_30_16_groupi_n_74),
	.A(csa_tree_add1_add_30_16_groupi_n_64),
	.B(csa_tree_add1_add_30_16_groupi_n_46));
   sky130_osu_sc_18T_ms__xnor2_l csa_tree_add1_add_30_16_groupi_g438__2802 (.Y(csa_tree_add1_add_30_16_groupi_n_73),
	.A(FE_PHN21_sum_q_2),
	.B(csa_tree_add1_add_30_16_groupi_n_63));
   sky130_osu_sc_18T_ms__nor2_l csa_tree_add1_add_30_16_groupi_g439__1705 (.Y(csa_tree_add1_add_30_16_groupi_n_72),
	.A(csa_tree_add1_add_30_16_groupi_n_63),
	.B(sum_q[2]));
   sky130_osu_sc_18T_ms__nor2_1 csa_tree_add1_add_30_16_groupi_g440__5122 (.Y(csa_tree_add1_add_30_16_groupi_n_71),
	.A(csa_tree_add1_add_30_16_groupi_n_46),
	.B(csa_tree_add1_add_30_16_groupi_n_64));
   sky130_osu_sc_18T_ms__oai22_l csa_tree_add1_add_30_16_groupi_g441__8246 (.Y(csa_tree_add1_add_30_16_groupi_n_70),
	.A0(csa_tree_add1_add_30_16_groupi_n_57),
	.A1(csa_tree_add1_add_30_16_groupi_n_54),
	.B0(csa_tree_add1_add_30_16_groupi_n_0),
	.B1(csa_tree_add1_add_30_16_groupi_n_43));
   sky130_osu_sc_18T_ms__aoi21_l csa_tree_add1_add_30_16_groupi_g442__7098 (.Y(csa_tree_add1_add_30_16_groupi_n_69),
	.A0(csa_tree_add1_add_30_16_groupi_n_48),
	.A1(FE_PHN10_sum_q_5),
	.B0(csa_tree_add1_add_30_16_groupi_n_66));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g443__6131 (.Y(csa_tree_add1_add_30_16_groupi_n_68),
	.A(csa_tree_add1_add_30_16_groupi_n_56),
	.B(csa_tree_add1_add_30_16_groupi_n_57));
   sky130_osu_sc_18T_ms__nor2_l csa_tree_add1_add_30_16_groupi_g445__5115 (.Y(csa_tree_add1_add_30_16_groupi_n_66),
	.A(csa_tree_add1_add_30_16_groupi_n_52),
	.B(csa_tree_add1_add_30_16_groupi_n_60));
   sky130_osu_sc_18T_ms__aoi22_l csa_tree_add1_add_30_16_groupi_g446__7482 (.Y(csa_tree_add1_add_30_16_groupi_n_65),
	.A0(n_114),
	.A1(csa_tree_add1_add_30_16_groupi_n_44),
	.B0(sum_q[3]),
	.B1(csa_tree_add1_add_30_16_groupi_n_32));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g447__4733 (.Y(csa_tree_add1_add_30_16_groupi_n_64),
	.A(csa_tree_add1_add_30_16_groupi_n_50),
	.B(n_114));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g448__6161 (.Y(csa_tree_add1_add_30_16_groupi_n_63),
	.A(csa_tree_add1_add_30_16_groupi_n_49),
	.B(csa_tree_add1_add_30_16_groupi_n_21));
   sky130_osu_sc_18T_ms__xnor2_l csa_tree_add1_add_30_16_groupi_g449__9315 (.Y(csa_tree_add1_add_30_16_groupi_n_62),
	.A(sum_q[5]),
	.B(csa_tree_add1_add_30_16_groupi_n_48));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g450__9945 (.Y(sum[1]),
	.A(csa_tree_add1_add_30_16_groupi_n_47),
	.B(csa_tree_add1_add_30_16_groupi_n_28));
   sky130_osu_sc_18T_ms__nor2_l csa_tree_add1_add_30_16_groupi_g451__2883 (.Y(csa_tree_add1_add_30_16_groupi_n_60),
	.A(csa_tree_add1_add_30_16_groupi_n_48),
	.B(sum_q[5]));
   sky130_osu_sc_18T_ms__aoi21_l csa_tree_add1_add_30_16_groupi_g452__2346 (.Y(csa_tree_add1_add_30_16_groupi_n_59),
	.A0(csa_tree_add1_add_30_16_groupi_n_33),
	.A1(FE_PHN1_sum_q_1),
	.B0(csa_tree_add1_add_30_16_groupi_n_53));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g454__7410 (.Y(csa_tree_add1_add_30_16_groupi_n_57),
	.A(csa_tree_add1_add_30_16_groupi_n_34),
	.B(csa_tree_add1_add_30_16_groupi_n_41));
   sky130_osu_sc_18T_ms__mux2_1 csa_tree_add1_add_30_16_groupi_g455__6417 (.Y(csa_tree_add1_add_30_16_groupi_n_56),
	.A0(csa_tree_add1_add_30_16_groupi_n_0),
	.A1(sum_q[4]),
	.S0(csa_tree_add1_add_30_16_groupi_n_43));
   sky130_osu_sc_18T_ms__xnor2_l csa_tree_add1_add_30_16_groupi_g456__5477 (.Y(csa_tree_add1_add_30_16_groupi_n_55),
	.A(csa_tree_add1_add_30_16_groupi_n_36),
	.B(csa_tree_add1_add_30_16_groupi_n_42));
   sky130_osu_sc_18T_ms__and2_l csa_tree_add1_add_30_16_groupi_g457__2398 (.Y(csa_tree_add1_add_30_16_groupi_n_54),
	.A(csa_tree_add1_add_30_16_groupi_n_0),
	.B(csa_tree_add1_add_30_16_groupi_n_43));
   sky130_osu_sc_18T_ms__nor2_l csa_tree_add1_add_30_16_groupi_g458__5107 (.Y(csa_tree_add1_add_30_16_groupi_n_53),
	.A(csa_tree_add1_add_30_16_groupi_n_45),
	.B(csa_tree_add1_add_30_16_groupi_n_28));
   sky130_osu_sc_18T_ms__aoi22_l csa_tree_add1_add_30_16_groupi_g459__6260 (.Y(csa_tree_add1_add_30_16_groupi_n_52),
	.A0(csa_tree_add1_add_30_16_groupi_n_34),
	.A1(csa_tree_add1_add_30_16_groupi_n_39),
	.B0(csa_tree_add1_add_30_16_groupi_n_23),
	.B1(csa_tree_add1_add_30_16_groupi_n_13));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g461__8428 (.Y(csa_tree_add1_add_30_16_groupi_n_50),
	.A(sum_q[3]),
	.B(csa_tree_add1_add_30_16_groupi_n_32));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g462__5526 (.Y(csa_tree_add1_add_30_16_groupi_n_49),
	.A(csa_tree_add1_add_30_16_groupi_n_35),
	.B(csa_tree_add1_add_30_16_groupi_n_4));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g463__6783 (.Y(csa_tree_add1_add_30_16_groupi_n_48),
	.A(csa_tree_add1_add_30_16_groupi_n_26),
	.B(csa_tree_add1_add_30_16_groupi_n_30));
   sky130_osu_sc_18T_ms__xnor2_l csa_tree_add1_add_30_16_groupi_g464__3680 (.Y(csa_tree_add1_add_30_16_groupi_n_47),
	.A(FE_PHN1_sum_q_1),
	.B(csa_tree_add1_add_30_16_groupi_n_33));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g465__1617 (.Y(csa_tree_add1_add_30_16_groupi_n_46),
	.A(csa_tree_add1_add_30_16_groupi_n_31),
	.B(csa_tree_add1_add_30_16_groupi_n_24));
   sky130_osu_sc_18T_ms__nor2_l csa_tree_add1_add_30_16_groupi_g466__2802 (.Y(csa_tree_add1_add_30_16_groupi_n_45),
	.A(csa_tree_add1_add_30_16_groupi_n_33),
	.B(FE_PHN1_sum_q_1));
   sky130_osu_sc_18T_ms__or2_l csa_tree_add1_add_30_16_groupi_g467__1705 (.Y(csa_tree_add1_add_30_16_groupi_n_44),
	.A(csa_tree_add1_add_30_16_groupi_n_32),
	.B(sum_q[3]));
   sky130_osu_sc_18T_ms__aoi22_l csa_tree_add1_add_30_16_groupi_g468__5122 (.Y(csa_tree_add1_add_30_16_groupi_n_43),
	.A0(csa_tree_add1_add_30_16_groupi_n_24),
	.A1(csa_tree_add1_add_30_16_groupi_n_20),
	.B0(csa_tree_add1_add_30_16_groupi_n_14),
	.B1(csa_tree_add1_add_30_16_groupi_n_6));
   sky130_osu_sc_18T_ms__oai21_l csa_tree_add1_add_30_16_groupi_g469__8246 (.Y(csa_tree_add1_add_30_16_groupi_n_42),
	.A0(csa_tree_add1_add_30_16_groupi_n_12),
	.A1(csa_tree_add1_add_30_16_groupi_n_15),
	.B0(csa_tree_add1_add_30_16_groupi_n_40));
   sky130_osu_sc_18T_ms__xnor2_l csa_tree_add1_add_30_16_groupi_g470__7098 (.Y(csa_tree_add1_add_30_16_groupi_n_41),
	.A(csa_tree_add1_add_30_16_groupi_n_23),
	.B(csa_tree_add1_add_30_16_groupi_n_13));
   sky130_osu_sc_18T_ms__nand2_l csa_tree_add1_add_30_16_groupi_g471__6131 (.Y(csa_tree_add1_add_30_16_groupi_n_40),
	.A(csa_tree_add1_add_30_16_groupi_n_26),
	.B(csa_tree_add1_add_30_16_groupi_n_25));
   sky130_osu_sc_18T_ms__or2_l csa_tree_add1_add_30_16_groupi_g472__1881 (.Y(csa_tree_add1_add_30_16_groupi_n_39),
	.A(csa_tree_add1_add_30_16_groupi_n_13),
	.B(csa_tree_add1_add_30_16_groupi_n_23));
   sky130_osu_sc_18T_ms__aoi21_l csa_tree_add1_add_30_16_groupi_g474__5115 (.Y(sum[0]),
	.A0(csa_tree_add1_add_30_16_groupi_n_19),
	.A1(csa_tree_add1_add_30_16_groupi_n_1),
	.B0(csa_tree_add1_add_30_16_groupi_n_27));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g475__7482 (.Y(csa_tree_add1_add_30_16_groupi_n_36),
	.A(sum_q[6]),
	.B(csa_tree_add1_add_30_16_groupi_n_5));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g476__4733 (.Y(csa_tree_add1_add_30_16_groupi_n_31),
	.A(csa_tree_add1_add_30_16_groupi_n_14),
	.B(csa_tree_add1_add_30_16_groupi_n_6));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g477__6161 (.Y(csa_tree_add1_add_30_16_groupi_n_30),
	.A(csa_tree_add1_add_30_16_groupi_n_12),
	.B(csa_tree_add1_add_30_16_groupi_n_15));
   sky130_osu_sc_18T_ms__xnor2_l csa_tree_add1_add_30_16_groupi_g478__9315 (.Y(csa_tree_add1_add_30_16_groupi_n_35),
	.A(csa_tree_add1_add_30_16_groupi_n_10),
	.B(csa_tree_add1_add_30_16_groupi_n_11));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g479__9945 (.Y(csa_tree_add1_add_30_16_groupi_n_34),
	.A(csa_tree_add1_add_30_16_groupi_n_7),
	.B(csa_tree_add1_add_30_16_groupi_n_18));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g480__2883 (.Y(csa_tree_add1_add_30_16_groupi_n_33),
	.A(csa_tree_add1_add_30_16_groupi_n_9),
	.B(csa_tree_add1_add_30_16_groupi_n_17));
   sky130_osu_sc_18T_ms__xor2_l csa_tree_add1_add_30_16_groupi_g481__2346 (.Y(csa_tree_add1_add_30_16_groupi_n_32),
	.A(csa_tree_add1_add_30_16_groupi_n_16),
	.B(csa_tree_add1_add_30_16_groupi_n_8));
   sky130_osu_sc_18T_ms__inv_1 csa_tree_add1_add_30_16_groupi_g483 (.Y(csa_tree_add1_add_30_16_groupi_n_28),
	.A(csa_tree_add1_add_30_16_groupi_n_27));
   sky130_osu_sc_18T_ms__nor2_1 csa_tree_add1_add_30_16_groupi_g484__1666 (.Y(csa_tree_add1_add_30_16_groupi_n_27),
	.A(csa_tree_add1_add_30_16_groupi_n_19),
	.B(csa_tree_add1_add_30_16_groupi_n_1));
   sky130_osu_sc_18T_ms__nor2_1 csa_tree_add1_add_30_16_groupi_g485__7410 (.Y(csa_tree_add1_add_30_16_groupi_n_26),
	.A(csa_tree_add1_add_30_16_groupi_n_18),
	.B(csa_tree_add1_add_30_16_groupi_n_7));
   sky130_osu_sc_18T_ms__nand2_l csa_tree_add1_add_30_16_groupi_g486__6417 (.Y(csa_tree_add1_add_30_16_groupi_n_25),
	.A(csa_tree_add1_add_30_16_groupi_n_15),
	.B(csa_tree_add1_add_30_16_groupi_n_12));
   sky130_osu_sc_18T_ms__nor2_1 csa_tree_add1_add_30_16_groupi_g487__5477 (.Y(csa_tree_add1_add_30_16_groupi_n_24),
	.A(csa_tree_add1_add_30_16_groupi_n_10),
	.B(csa_tree_add1_add_30_16_groupi_n_11));
   sky130_osu_sc_18T_ms__nor2_1 csa_tree_add1_add_30_16_groupi_g488__2398 (.Y(csa_tree_add1_add_30_16_groupi_n_23),
	.A(csa_tree_add1_add_30_16_groupi_n_16),
	.B(csa_tree_add1_add_30_16_groupi_n_8));
   sky130_osu_sc_18T_ms__nor2_1 csa_tree_add1_add_30_16_groupi_g490__5107 (.Y(csa_tree_add1_add_30_16_groupi_n_21),
	.A(csa_tree_add1_add_30_16_groupi_n_17),
	.B(csa_tree_add1_add_30_16_groupi_n_9));
   sky130_osu_sc_18T_ms__or2_l csa_tree_add1_add_30_16_groupi_g491__6260 (.Y(csa_tree_add1_add_30_16_groupi_n_20),
	.A(csa_tree_add1_add_30_16_groupi_n_6),
	.B(csa_tree_add1_add_30_16_groupi_n_14));
   sky130_osu_sc_18T_ms__nand2_1 csa_tree_add1_add_30_16_groupi_g492__4319 (.Y(csa_tree_add1_add_30_16_groupi_n_19),
	.A(b[0]),
	.B(a[0]));
   sky130_osu_sc_18T_ms__nand2_1 csa_tree_add1_add_30_16_groupi_g493__8428 (.Y(csa_tree_add1_add_30_16_groupi_n_18),
	.A(b[3]),
	.B(a[1]));
   sky130_osu_sc_18T_ms__nand2_1 csa_tree_add1_add_30_16_groupi_g494__5526 (.Y(csa_tree_add1_add_30_16_groupi_n_17),
	.A(a[0]),
	.B(b[1]));
   sky130_osu_sc_18T_ms__nand2_1 csa_tree_add1_add_30_16_groupi_g495__6783 (.Y(csa_tree_add1_add_30_16_groupi_n_16),
	.A(b[3]),
	.B(a[0]));
   sky130_osu_sc_18T_ms__nand2_1 csa_tree_add1_add_30_16_groupi_g496__3680 (.Y(csa_tree_add1_add_30_16_groupi_n_15),
	.A(b[2]),
	.B(a[3]));
   sky130_osu_sc_18T_ms__and2_1 csa_tree_add1_add_30_16_groupi_g497__1617 (.Y(csa_tree_add1_add_30_16_groupi_n_14),
	.A(a[1]),
	.B(b[2]));
   sky130_osu_sc_18T_ms__and2_1 csa_tree_add1_add_30_16_groupi_g498__2802 (.Y(csa_tree_add1_add_30_16_groupi_n_13),
	.A(b[2]),
	.B(a[2]));
   sky130_osu_sc_18T_ms__nand2_1 csa_tree_add1_add_30_16_groupi_g499__1705 (.Y(csa_tree_add1_add_30_16_groupi_n_12),
	.A(b[3]),
	.B(a[2]));
   sky130_osu_sc_18T_ms__nand2_1 csa_tree_add1_add_30_16_groupi_g500__5122 (.Y(csa_tree_add1_add_30_16_groupi_n_11),
	.A(b[0]),
	.B(a[2]));
   sky130_osu_sc_18T_ms__nand2_1 csa_tree_add1_add_30_16_groupi_g501__8246 (.Y(csa_tree_add1_add_30_16_groupi_n_10),
	.A(b[2]),
	.B(a[0]));
   sky130_osu_sc_18T_ms__nand2_1 csa_tree_add1_add_30_16_groupi_g502__7098 (.Y(csa_tree_add1_add_30_16_groupi_n_9),
	.A(b[0]),
	.B(a[1]));
   sky130_osu_sc_18T_ms__nand2_1 csa_tree_add1_add_30_16_groupi_g503__6131 (.Y(csa_tree_add1_add_30_16_groupi_n_8),
	.A(b[0]),
	.B(a[3]));
   sky130_osu_sc_18T_ms__nand2_l csa_tree_add1_add_30_16_groupi_g504__1881 (.Y(csa_tree_add1_add_30_16_groupi_n_7),
	.A(b[1]),
	.B(a[3]));
   sky130_osu_sc_18T_ms__and2_1 csa_tree_add1_add_30_16_groupi_g505__5115 (.Y(csa_tree_add1_add_30_16_groupi_n_6),
	.A(b[1]),
	.B(a[2]));
   sky130_osu_sc_18T_ms__and2_1 csa_tree_add1_add_30_16_groupi_g506__7482 (.Y(csa_tree_add1_add_30_16_groupi_n_5),
	.A(b[3]),
	.B(a[3]));
   sky130_osu_sc_18T_ms__nand2_1 csa_tree_add1_add_30_16_groupi_g507__4733 (.Y(csa_tree_add1_add_30_16_groupi_n_4),
	.A(b[1]),
	.B(a[1]));
   sky130_osu_sc_18T_ms__inv_1 csa_tree_add1_add_30_16_groupi_g510 (.Y(csa_tree_add1_add_30_16_groupi_n_0),
	.A(sum_q[4]));
   sky130_osu_sc_18T_ms__inv_1 csa_tree_add1_add_30_16_groupi_g513 (.Y(csa_tree_add1_add_30_16_groupi_n_1),
	.A(sum_q[0]));
   sky130_osu_sc_18T_ms__xnor2_l g2 (.Y(n_112),
	.A(n_111),
	.B(FE_PHN22_sum_q_7));
   sky130_osu_sc_18T_ms__aoi21_l g3 (.Y(n_111),
	.A0(FE_PHN9_sum_q_6),
	.A1(csa_tree_add1_add_30_16_groupi_n_5),
	.B0(csa_tree_add1_add_30_16_groupi_n_42));
   sky130_osu_sc_18T_ms__or2_1 g515 (.Y(n_114),
	.A(n_113),
	.B(csa_tree_add1_add_30_16_groupi_n_21));
   sky130_osu_sc_18T_ms__nor2_1 g516 (.Y(n_113),
	.A(csa_tree_add1_add_30_16_groupi_n_35),
	.B(csa_tree_add1_add_30_16_groupi_n_4));
endmodule

